# Generated by Django 5.1.1 on 2024-09-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cover_avatar',
        ),
    ]
