# Generated by Django 5.1.1 on 2024-09-26 14:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0002_remove_account_cover_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.account'),
        ),
        migrations.CreateModel(
            name='ProductPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('post_content', ckeditor.fields.RichTextField()),
                ('comment_lock', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.account')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.product')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
