# Generated by Django 5.1.1 on 2024-09-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0003_remove_post_product_alter_product_owner_productpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productpost',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpost',
            name='post_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/product_post_images/%Y/%m'),
        ),
    ]
