# Generated by Django 5.1.1 on 2024-10-03 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0004_alter_post_options_alter_productpost_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreaction',
            options={},
        ),
        migrations.CreateModel(
            name='ProductPostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.account')),
                ('product_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.productpost')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_social_media_app.reaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
