# Generated by Django 5.1.1 on 2024-10-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_lock',
        ),
        migrations.RemoveField(
            model_name='productpost',
            name='comment_lock',
        ),
    ]
