# Generated by Django 5.1.1 on 2024-10-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0008_alter_account_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
