# Generated by Django 5.1.1 on 2024-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_social_media_app', '0009_delete_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpoll',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='postpoll',
            name='start_time',
            field=models.DateField(),
        ),
    ]
